logging:
  level:
    org:
#      springframework: debug
      hibernate:
        type: trace

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true